# Generated by Django 4.1.3 on 2022-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('symbol', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=10, null=True)),
                ('price', models.IntegerField()),
                ('change', models.FloatField()),
            ],
        ),
    ]
