# Generated by Django 4.1.3 on 2022-11-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StocksData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('cost', models.FloatField()),
                ('symbolKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StocksData.stocks')),
            ],
        ),
    ]
