# Generated by Django 4.1.3 on 2022-11-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StocksData', '0001_initial'),
        ('InsiderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidertransaction',
            name='symbolKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbolKey', to='StocksData.stocks'),
        ),
    ]
