# Generated by Django 4.1.3 on 2022-11-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsiderApp', '0002_alter_insidertransaction_symbolkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidertransaction',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
